# Generated by Django 5.0.6 on 2024-06-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_system_transaction',
            field=models.BooleanField(default=False),
        ),
    ]
