# Generated by Django 5.0.6 on 2024-06-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doscointbalance',
            name='total_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
