# Generated by Django 5.0.6 on 2024-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='campaigns/qr_codes/'),
        ),
    ]
